Added a method of disabling individual checks via git config.

diff --git a/pre-commit_AllowBlanksInFileNames_WIP b/pre-commit_AllowBlanksInFileNames_WIP
--- a/pre-commit_AllowBlanksInFileNames_WIP
+++ b/pre-commit_AllowBlanksInFileNames_WIP
@@ -13,20 +13,13 @@
 # wants to stop the commit.
 #
 # The script checks for:
-#   * Non-ASCII character file names
-#   (Disable with $ git config hooks.allownonascii true)
-#   * Compliance with uncrustify coding standards
-#   (Disable with $ git config hooks.allownocodeconventions true)
-#   * Line lengths greater than 80 characters
-#   (Disable with $ git config hooks.allowovereightychars true)
-#   * Tab characters
-#   (Disable with $ git config hooks.allowtabchars true)
-#   * Trailing whitespace
-#   (Disable with $ git config hooks.allowtrailingwhitespace true)
-#   * DOS line endings
-#   (Disable with $ git config hooks.allowdosnewlines true)
-#   * Copyright check
-#   (Disable with $ git config hooks.allownocopyright true)
+#   Non-ASCII character file names
+#   Compliance with uncrustify coding standards
+#   Line lengths greater than 80 characters
+#   Tab characters
+#   Trailing whitespace
+#   DOS line endings
+#   Copyright check
 #
 # CALLING SEQUENCE      Called by "git commit"
 #
@@ -72,14 +65,12 @@
 # Directories to ignore
 # Ignore old style revision control system "RCS" directories
 #EXEMPT_DIR_NAMES="RCS" # This normally should be done with a .gitignore file
-# These directories don't follow our coding standards
+# These directories doesn't follow our coding standards
 #EXEMPT_DIR_NAMES="MAX MAX_PS Execute GDS_Data GDS_Max"
-EXEMPT_DIR_NAMES="TestCases"
 
 # File types NOT to put through all checks because the 80 char line
 # length limit and tab character checks will give false positives.
-EXEMPT_FILE_EXTS=".exe .gz .tgz .xz .zip .ico .csv .html .xml .md .cfg .pdf" \
-" .out"
+EXEMPT_FILE_EXTS=".exe .gz .tgz .xz .zip .ico .csv .html .xml .md .cfg"
 
 # File types to perform uncrustify checks on
 FILE_EXTS=".c .h .cc .cpp .hpp"
@@ -98,17 +89,18 @@ CONFIG="$HOME/uncrustify/mms.cfg"
 # Copyright (c) FirstYear, CurrentYear, $COPYRIGHT_HOLDER.
 # with the "(c)" and first year being optional and the
 # current year and closing period mandatory.
-# Example #1
 # COPYRIGHT_HOLDER="Daniel C. Nygren"
-# Example #2
 # COPYRIGHT_HOLDER="example.com and/or its affiliates"
-
 # Files exempt from copyright check
 EXEMPT_FROM_COPYRIGHT="LICENSE"
 
 # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 # ^^^^^^^^^^ Place code that may need modification above this point. ^^^^^^^^^^
 # ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+
+# Change the internal field separator so we can say "for $file in ... do" when
+# there are spaces in filenames.
+IFS=$'\n'
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
@@ -118,21 +110,24 @@ else
     against=$(git hash-object -t tree /dev/null)
 fi
 
-added_modded_files=$(git status --short | grep -E '^(A|M)' | awk '{ print $2 }')
-
-# Redirect output to stderr.
-exec 1>&2
+added_modded_files=$(git status --short \
+| grep -E '^(A|M)' \
+| awk '{ $1=""; print}' \
+| sed -e 's/[[:blank:]]*//' \
+| sed -e 's/^"//' -e 's/"$//' )
+# echo -e "Added Modded files:\n$added_modded_files"
 
 ##################################################################
 # If you want to allow non-ASCII filenames set this variable to true.
 allownonascii=$(git config --bool hooks.allownonascii)
 
+# Redirect output to stderr.
+exec 1>&2
+
 # Cross platform projects tend to avoid non-ASCII filenames; prevent
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-    ##################################################################
-    # If there are non-ASCII file names, print error message and fail.
     # Note that the use of brackets around a tr range is ok here, (it's
     # even required, for portability to Solaris 10's /usr/bin/tr), since
     # the square bracket bytes happen to fall in the designated range.
@@ -147,20 +142,13 @@ If you know what you are doing you can disable this check using:
   git config hooks.allownonascii true
 EOF
     exit 1 # Exit failure
-fi # allownonascii
+fi
 
 ##################################################################
 # Print directories exempt from all checks.
 #
 echo "### File in the following directories are exempt from ALL checks: ###"
 echo $EXEMPT_DIR_NAMES
-
-##################################################################
-# If you want to allow files that don't comply with code conventions,
-# set this variable to true.
-allownocodeconventions=$(git config --bool hooks.allownocodeconventions)
-if [ "$allownocodeconventions" != "true" ]
-then
 
 ##################################################################
 # If files don't comply with code conventions, print them and fail.
@@ -175,12 +163,19 @@ echo "### Attempting to validate the coding conventions. ###"
 
 # Check whether the given file matches any of the set extensions
 matches_extension() {
+#    echo "File passed to matches_extension() = $1"
     local filename="$(basename -- "$1")"
-    local extension=".${filename##*.}"
-    local ext
+#    echo "Basename of file in matches_extension() = $filename"
+    if [[ $filename =~ \. ]]
+    then
+        echo "Extension check filename $filename"
+        local extension=".${filename##*.}"
+        echo "Extension check extension $extension"
+        local ext
 
-    for ext in $FILE_EXTS; do [ "$ext" = "$extension" ] && return 0; done
-    # return 0 is success (matches)
+        for ext in $FILE_EXTS; do [ "$ext" = "$extension" ] && return 0; done
+        # return 0 is success (matches)
+    fi
     return 1
 }
 
@@ -232,14 +227,14 @@ matches_exempt_from_copyright() {
 
 # Make sure the uncrustify config file and executable are correctly set
 if [ ! -f "$CONFIG" ] ; then
-    printf "Error: uncrustify config file $CONFIG not found.\n"
-    printf "Install or set the correct path in "$0".\n"
+    echo "Error: uncrustify config file $CONFIG not found."
+    echo "Install or set the correct path in "$0"."
     exit 1 # Exit failure
 fi
 
 if ! command -v "$UNCRUSTIFY" > /dev/null ; then
-    printf "Error: uncrustify executable $UNCRUSTIFY not found.\n"
-    printf "Install or set the correct path in "$0".\n"
+    echo "Error: uncrustify executable $UNCRUSTIFY not found."
+    echo "Install or set the correct path in "$0"."
     exit 1 # Exit failure
 fi
 
@@ -249,35 +244,32 @@ for file in $added_modded_files; do
     if ! matches_dir "$file" ; then
         # Check file if it matches any of the extensions in $FILE_EXTS
         if matches_extension "$file"; then
-            printf "Checking $file because its extension matches $FILE_EXTS\n"
-            $UNCRUSTIFY --check -c $CONFIG -f $file
+            echo "Checking $file because its extension matches $FILE_EXTS"
+            $UNCRUSTIFY --check -c $CONFIG -f "$file"
             if [ $? -ne 0 ] ; then
-                $UNCRUSTIFY -q -c $CONFIG -f $file > /tmp/`basename $file `
-                full_path_to_file=$(/usr/bin/realpath $file)
-                echo -n "-> Compare files or copy uncrustified temporary file "
-                echo " over the existing file with below commands."
-                echo " gvimdiff /tmp/`basename $file` $full_path_to_file"
-                echo " cp /tmp/`basename $file` $full_path_to_file"
+                $UNCRUSTIFY -q -c $CONFIG -f "$file" > /tmp/`basename "$file" `
+                full_path_to_file=$(/usr/bin/realpath "$file")
+                echo -n "-> Compare files with below command or copy "
+                echo "uncrustified temporary file to existing file."
+                echo " gvimdiff /tmp/`basename "$file"` $full_path_to_file"
                 EXIT_VALUE=1
             fi
         else
-            echo "$file exempt because its extension didn't match $FILE_EXTS"
+            echo "$file is exempt because its extension didn't match $FILE_EXTS"
         fi
     else
-        printf "$file exempt because its directory matched $EXEMPT_DIR_NAMES\n"
+        echo "$file is exempt because its directory matched $EXEMPT_DIR_NAMES"
     fi
 done
 
 if [ $EXIT_VALUE -eq 1 ]
 then
     echo "Exiting because a $UNCRUSTIFY --check -c $CONFIG -f <file> failed."
-    printf "***Remember to \"git add <changed file>\" before trying again.***\n"
+    echo "***Remember to \"git add <changed file>\" before trying again.***"
     exit 1 # Exit failure
 else
-    printf "Non-exempt file(s) comply.\n"
+    echo "Non-exempt file(s) comply."
 fi
-
-fi # allownocodeconventions
 
 ##################################################################
 # Reuse the matches_extension function using exempt file extensions.
@@ -285,12 +277,6 @@ fi # allownocodeconventions
 FILE_EXTS=$EXEMPT_FILE_EXTS
 echo "### File extensions exempt from the following checks: ###"
 echo $EXEMPT_FILE_EXTS
-
-##################################################################
-# If you want to allow lines > 80 set this variable to true.
-allowovereightychars=$(git config --bool hooks.allowovereightychars)
-if [ "$allowovereightychars" != "true" ]
-then
 
 ##################################################################
 # If there are files with lines > 80 characters, print them and fail.
@@ -307,7 +293,7 @@ EXIT_VALUE=0
 for file in $added_modded_files; do
     # Don't check EXEMPT_FILE_EXTS or EXEMPT_DIR_NAMES
     if !(matches_extension "$file") && !(matches_dir "$file"); then
-        if grep --line-number --with-filename '.\{81,\}' $file ; then
+        if grep --line-number --with-filename '.\{81,\}' "$file" ; then
             # If any files match, exit after checking all files
             EXIT_VALUE=1
         fi
@@ -318,13 +304,11 @@ done
 if [ $EXIT_VALUE -eq 1 ]
     then
     echo "Exiting because 80 character line length exceeded."
-    printf "***Remember to \"git add <changed file>\" before trying again.***\n"
+    echo "***Remember to \"git add <changed file>\" before trying again.***"
     exit 1 # Exit failure
 else
-    printf "Non-exempt file(s) comply.\n"
+    echo "Non-exempt file(s) comply."
 fi
-
-fi # allowovereightychars
 
 ##################################################################
 
@@ -337,11 +321,6 @@ fi # allowovereightychars
 # A complete git status --short line has extra space and extra data
 # at the beginning, so we want to remove that.
 # awk also performs automatic stripping.
-
-# If you want to allow tabs, set this variable to true.
-allowtabchars=$(git config --bool hooks.allowtabchars)
-if [ "$allowtabchars" != "true" ]
-then
 echo "### Attempting to validate the tab character prohibition. ###"
 
 # Now we can verify each file with a for loop:
@@ -354,8 +333,8 @@ for file in $added_modded_files; do
     fi
     # Don't check EXEMPT_FILE_EXTS or EXEMPT_DIR_NAMES
     if !(matches_extension "$file") && !(matches_dir "$file"); then
-        if grep --line-number --with-filename -P '\t' $file ; then
-        echo "Has a tab" $file
+        if grep --line-number --with-filename -P '\t' "$file" ; then
+        echo "Has a tab" "$file"
         # If any files match, exit after checking all files
             EXIT_VALUE=1
         fi
@@ -366,14 +345,11 @@ done
 if [ $EXIT_VALUE -eq 1 ]
 then
     echo "Exiting because a file with a tab character was found."
-    printf "***Remember to \"git add <changed file>\" before trying again.***\n"
+    echo "***Remember to \"git add <changed file>\" before trying again.***"
     exit 1 # Exit failure
 else
-    printf "Non-exempt file(s) comply.\n"
+    echo "Non-exempt file(s) comply."
 fi
-
-fi # allowtabchars
-
 ##################################################################
 
 ##################################################################
@@ -387,10 +363,6 @@ fi # allowtabchars
 #echo "### Validation there is no trailing whitespace. ###"
 #exec git diff-index --check --cached $against --
 
-allowtrailingwhitespace=$(git config --bool hooks.allowtrailingwhitespace)
-if [ "$allowtrailingwhitespace" != "true" ]
-then
-
 echo "### Attempting to validate the trailing whitespace prohibition. ###"
 
 # Now we can verify each file with a for loop:
@@ -398,7 +370,7 @@ EXIT_VALUE=0
 for file in $added_modded_files; do
     # Don't check EXEMPT_FILE_EXTS or EXEMPT_DIR_NAMES
     if !(matches_extension "$file") && !(matches_dir "$file"); then
-        if grep --line-number --with-filename '[[:blank:]]$' $file ; then
+        if grep --line-number --with-filename '[[:blank:]]$' "$file" ; then
         # If any files match, exit after checking all files
             EXIT_VALUE=1
         fi
@@ -409,25 +381,18 @@ done
 if [ $EXIT_VALUE -eq 1 ]
 then
     echo "Exiting because a file with trailing whitespace was found."
-    printf "***Remember to \"git add <changed file>\" before trying again.***\n"
+    echo "***Remember to \"git add <changed file>\" before trying again.***"
     exit 1 # Exit failure
 else
-    printf "Non-exempt file(s) comply.\n"
+    echo "Non-exempt file(s) comply."
 fi
 
-fi # allowtrailingwhitespace"
-
 ##################################################################
-
-##################################################################
-# If you want to allow dos newlines, set this variable to true.
-allowdosnewlines=$(git config --bool hooks.allowdosnewlines)
-if [ "$allowdosnewlines" != "true" ]
-then
 
 ##################################################################
 # If there are dos newlines, print the offending lines and file names.
 #
+
 echo "### Attempting to validate the Unix newline requirement. ###"
 
 # Now we can verify each file with a for loop:
@@ -435,7 +400,7 @@ EXIT_VALUE=0
 for file in $added_modded_files; do
     # Don't check EXEMPT_FILE_EXTS or EXEMPT_DIR_NAMES
     if !(matches_extension "$file") && !(matches_dir "$file"); then
-        if grep --line-number --with-filename $'\r' $file ; then
+        if grep --line-number --with-filename $'\r' "$file" ; then
         # If any files match, exit after checking all files
             EXIT_VALUE=1
         fi
@@ -446,21 +411,13 @@ done
 if [ $EXIT_VALUE -eq 1 ]
 then
     echo "Exiting because a file with a DOS newline was found."
-    printf "***Remember to \"git add <changed file>\" before trying again.***\n"
+    echo "***Remember to \"git add <changed file>\" before trying again.***"
     exit 1 # Exit failure
 else
-    printf "Non-exempt file(s) comply.\n"
+    echo "Non-exempt file(s) comply."
 fi
 
-fi # allowdosnewlines
-
 ##################################################################
-
-##################################################################
-# If you want to allow dos newlines, set this variable to true.
-allownocopyright=$(git config --bool hooks.allownocopyright)
-if [ "$allownocopyright" != "true" ]
-then
 
 ##################################################################
 # If files do not contain compliant copyright notices, print the
@@ -509,12 +466,12 @@ then
             # -r  use extended regular expressions
             matches=$(/bin/sed -nr "$COPYRIGHT_LINE_RE" "$file")
             if [[ -z "$matches" ]]; then
-                full_path_to_file=$(/usr/bin/realpath $file)
+                full_path_to_file=$(/usr/bin/realpath "$file")
                 echo "$full_path_to_file - Non-existent or non-matching \
 copyright line."
                 EXIT_VALUE=1
             elif [[ ! $matches =~ ^.*$CURRENT_YEAR.*$ ]]; then
-                full_path_to_file=$(/usr/bin/realpath $file)
+                full_path_to_file=$(/usr/bin/realpath "$file")
                 echo "$full_path_to_file - Copyright line does not contain \
 $CURRENT_YEAR."
                 EXIT_VALUE=1
@@ -527,17 +484,14 @@ $CURRENT_YEAR."
         echo "Exiting because a file had a copyright line error."
         echo "Copyright lines must follow the form:"
         echo "Copyright (c) FirstYear, $CURRENT_YEAR, $COPYRIGHT_HOLDER."
-        printf "***Remember to \"git add <changed file>\" before trying \
-again.***\n"
+        echo "***Remember to \"git add <changed file>\" before trying \
+again.***"
         exit 1 # Exit failure
     else
-        printf "Non-exempt file(s) comply.\n"
+        echo "Non-exempt file(s) comply."
     fi
 else
-    printf "Copyright header checks were not performed because the \
-COPYRIGHT_HOLDER is undefined.\n"
+    echo "Copyright header checks were not performed because the \
+COPYRIGHT_HOLDER is undefined."
 fi
-
-fi # allownocopyright
-
 ##################################################################
